services:
  verbex-server:
    image: jchristn77/verbex-server:v0.2.1
    container_name: verbex-server
    ports:
      - "8080:8080"
    volumes:
      - ./server/verbex.json:/app/verbex.json
      - ./server/db/:/app/db/
      - ./server/data/:/app/data/
      - ./server/logs/:/app/logs/
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/v1.0/health"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 30s
